name: Test

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Generate prisma client
        run: npx prisma generate

      - name: Build Nuxt
        run: npm run build

      - name: Copy platform specific prisma client
        run: cp generated/prisma/libquery_engine-debian-openssl-1.0.x.so.node .output/server
        
      - name: Archive build
        run: zip -r output.zip .output

      - name: Upload to VPS via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "output.zip"
          target: "/home/hardstylegg/deploy"
